export const INCREMENT_COUNT = "INCREMENT_COUNT";
export const DECREMENT_COUNT = "DECREMENT_COUNT";
export const SET_COUNT = "SET_COUNT";
export const RESET_COUNT = "RESET_COUNT";
export const CHANGE_BACKGROUND_COLOR = "CHANGE_BACKGROUND_COLOR";
